### ISSUE TITLE
old_materialized_path doesn't seem to be implemented

### ISSUE THREAD

**Issue by seandunn** [Bramjetten/Spina-Blog-Example#1]
Just tried playing with the blog plugin.

I'm hitting an error on old_materialized_path= not being implemented in blogpost.rb

Is this missing from a migration maybe?

**Comment by Bramjetten** [comment]
You're right! attr_accessor :old_slug should be :old_materialized_path.

**Comment by seandunn** [comment]
No worries. :) that was actually my next guess from looking at the schema.

**Comment by Bramjetten** [comment]
Just fixed it in the latest commit.
